import assert from 'node:assert/strict';
import { H6159, hsvToRgb } from './h6159.mjs';
import { Lighting } from './lighting.mjs';
const id='ble-a4c138fdb1b0', address='A4:C1:38:FD:B1:B0';
let actual={on:true,brightnessByte:38,mode:2,rgb:[80,5,255]}, fail=false;
const calls=[];
const request=async c=>{
  calls.push(c);
  if(fail) throw Error('Disconnected');
  if(c.action==='scan') return [{address,name:'ihoment_H6159_B1B0'}];
  if(c.action==='power') actual.on=c.on;
  if(c.action==='brightness') actual.brightnessByte=c.value;
  if(c.action==='color') Object.assign(actual,{mode:2,rgb:c.rgb});
  if(c.action==='restore') actual=structuredClone(c.state);
  return structuredClone(actual);
};
const l=new Lighting(); l.nodeIds=new Map(); l.settings={version:2,lights:{},groups:{tv:{name:'TV',members:[]}}};
l.save=async()=>{}; l.bleRequest=request;
await l.manage({type:'addBluetooth',address,name:'TV strip',room:'tv'});
assert(l.bulbs.get(id) instanceof H6159);
assert.deepEqual(l.members('tv'),[id]);
await assert.rejects(l.manage({type:'addBluetooth',address,name:'Duplicate',room:''}),/already/);
await assert.rejects(l.command({target:id,type:'fullWhite',enabled:true}),/unavailable/);
assert.equal((await l.command({target:'tv',type:'temperature',value:4400})).outcomes[0].skipped,true);
await assert.rejects(l.startMusic(id),/No available/);
await assert.rejects(l.gradient({target:id,enabled:true,start:{hue:0,saturation:100},end:{hue:120,saturation:100},duration:3000,repeat:'alternate'}));
const saved=structuredClone(actual);
await l.scene({type:'create',target:'tv',name:'Purple'});
const scene=Object.values(l.settings.scenes)[0];
await l.command({target:id,type:'color',hue:120,saturation:100});
assert.deepEqual(actual.rgb,[0,255,0]);
assert.equal(l.sceneList((await l.catalog()).lights)[0].active,false);
await l.scene({type:'apply',id:scene.id});
assert.deepEqual(actual,saved);
assert.equal(l.sceneList((await l.catalog()).lights)[0].active,true);
actual.mode=4;
await l.catalog(); // Observe the external effect before saving the last confirmed state.
await assert.rejects(l.scene({type:'create',target:'tv',name:'Effect'}),/not saved/);
actual.mode=2;
await assert.rejects(l.bulbs.get(id).restore({mode:0}),/Invalid/);
fail=true;
assert.equal((await l.catalog()).lights[0].available,false);
fail=false;
assert.equal((await l.retryBulbs([id])).lights[0].available,true);
assert.deepEqual(hsvToRgb(360,100),[255,0,0]);
assert.deepEqual(hsvToRgb(0,0),[255,255,255]);
const fresh=new H6159(id,l.settings.lights[id],request);
assert.equal((await fresh.read()).brightness,15);
const rollback=new Lighting(); rollback.nodeIds=new Map(); rollback.settings={version:2,lights:{},groups:{}};
rollback.bleRequest=request; rollback.save=async()=>{throw Error('Disk full');};
await assert.rejects(rollback.manage({type:'addBluetooth',address,name:'TV strip',room:''}),/Disk full/);
assert.equal(rollback.nodeIds.size,0);
assert.deepEqual(rollback.settings.lights,{});
// A mixed room still controls Matter white without touching the strip.
l.nodeIds.set('1',1n); l.settings.lights['1']={name:'Matter',restore:null,owner:null};
l.settings.groups.tv.members.push('1');
let white=0;
l.bulbs.set('1',{setWhite:async()=>{white++;},read:async()=>({id:'1',available:true})});
const before=calls.length;
const mixed=await l.command({target:'tv',type:'temperature',value:4400});
assert.equal(white,1);
assert.equal(mixed.outcomes.find(o=>o.id===id).skipped,true);
assert(calls.slice(before).every(c=>c.action==='read'));
console.log('PASS: H6159 addition, duplicate protection, capability gates, exact scene restoration, external effects, failures and recovery.');
